title: "Machine Learning for Scientific Discovery"
description: "ENS course materials"

# Theme
theme: minima

# Navigation
header_pages:
  - 4_optimization.md
  
# Math support with kramdown
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Enable MathJax
plugins:
  - jekyll-feed